language: shell
os: linux
dist: focal
arch: amd64

services:
  - docker

env:
  - UBUNTU_VERSION=bionic

jobs:
  include:
    - stage: build docker image
      script: docker build --build-arg "UBUNTU_VERSION=${UBUNTU_VERSION}" --tag deshifter/baseimage:${UBUNTU_VERSION} .
    - stage: push docker image
      script:
        - echo "$DOCKER_HUB_PASSWORD" | docker login --username "$(DOCKER_HUB_USER)" --password-stdin
        - docker push deshifter/baseimage:${UBUNTU_VERSION}
      if: branch = master

# Installing a newer Docker version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

notifications:
  webhooks: https://outlook.office.com/webhook/412d8b59-eb3f-46c3-b19b-3379ff4afbff@64811792-9fe4-4c75-aaa5-51d46a8e138d/TravisCI/92cf91ed98764aeebedf43783694ff51/aa538873-4971-440f-b1dc-f1ae79de641e
